version: "3.9"

services:
  mysql:
    image: mysql:latest
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    restart: always
    volumes:
      - db:/var/lib/mysql
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: wp_auth0_test
      MYSQL_DATABASE: wp_auth0_test
      MYSQL_USER: wp_auth0_test
      MYSQL_PASSWORD: wp_auth0_test

volumes:
  db: {}
